name: Orquestrador encadeamento dos 4 steps 
on:
  workflow_dispatch:
    inputs:
      text_in:
        description: Texto inicial
        required: true
        type: string
      number_in:
        description: Número inicial
        required: true
        type: number

jobs:
  step1:
    uses: ./.github/workflows/step1.yml
    with:
      text:   ${{ inputs.text_in }}
      number: ${{ fromJson(inputs.number_in) }}

  step2:
    needs: step1
    uses: ./.github/workflows/step2.yml
    with:
      text:   ${{ needs.step1.outputs.text_out }}
      number: ${{ fromJson(needs.step1.outputs.number_out) }}

  step3:
    needs: step2
    uses: ./.github/workflows/step3.yml
    with:
      text:   ${{ needs.step2.outputs.text_out }}
      number: ${{ fromJson(needs.step2.outputs.number_out) }}

  step4:
    needs: step3
    uses: ./.github/workflows/step4.yml
    with:
      text:   ${{ needs.step3.outputs.text_out }}
      number: ${{ fromJson(needs.step3.outputs.number_out) }}
