name: W2 reutilizável - Letra maiúscula e Soma 5
on:
 workflow_call:
  inputs:
      text_in:
        description: Texto de entrada
        required: true
        type: string
      number_in:
        description: Número de entrada
        required: true
        type: number
  outputs:
      text_out:
        description: Texto modificado
        value: ${{ jobs.transform.outputs.text_out }}
      number_out:
        description: Número modificado
        value: ${{  jobs.transform.outputs.number_out }}
jobs:
   transform:
     runs-on: ubuntu-latest
     outputs:
        text_out: ${{ steps.calc.outputs.text_out }}
        number_out: ${{ steps.calc.outputs.number_out }}
     steps:
      - id: calc
        shell: bash
        run: |
          TEXT="${{ inputs.text }}"
          NUM=${{ inputs.number }}
          NEW_TEXT="$(echo "$TEXT" | tr '[:lower:]' '[:upper:]')"
          NEW_NUM=$(( NUM + 5 ))
          echo "text_out=$NEW_TEXT"   >> "$GITHUB_OUTPUT"
          echo "number_out=$NEW_NUM" >> "$GITHUB_OUTPUT"
